"""add post table

Revision ID: 8e8a30f1a03a
Revises: 38ba69326d57
Create Date: 2023-04-17 13:09:03.699338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8a30f1a03a'
down_revision = '38ba69326d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemon', sa.String(length=25), nullable=False),
    sa.Column('evolutions', sa.String(length=50), nullable=False),
    sa.Column('strengths', sa.String(length=25), nullable=False),
    sa.Column('weaknesses', sa.String(length=25), nullable=False),
    sa.Column('image_url', sa.String(length=150), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
